### ISSUE TITLE
About foundation models

### ISSUE THREAD

**Issue by junkunyuan** [BradyFU/Awesome-Multimodal-Large-Language-Models#63]
What is the classification basis for the category of "Foundation Models"? For example, why flamingo and mPLUG-Owl are not foundation models?

**Comment by BradyFU** [comment]
Thanks. At present, the fundation model refers to the work on which others can easily do secondary development or the work that is more fundamental instead of applied. 

Some works may belong to multiple classes, such as flamingo belongs to the fundation model and multimodal ICL. Here we only add it to the latter to avoid repetition. mPLUG-Owl is an applied work, and its method belongs to multmodal instruction tuning. 

There is a cross between different categories and we still try to give clearer definitions. By now, we usually classify them by one attribute.
